version: "3"
networks:
  geoQuiz.net:
    driver: bridge
services:
    geoQuiz.api.directus:
      image: 'canals/php:latest'
      ports:
        - '2080:80'
      volumes:
        - ./api:/var/www/html
        - ./api:/var/www
      working_dir: /var/www/html
      networks:
         geoQuiz.net:
           - aliases:
               - api.directus
      depends_on:
        - geoQuiz.db.directus

    geoQuiz.api.auth:
      image: 'canals/php:latest'
      ports:
        - '2081:80'
      volumes:
        - ./auth:/var/www/html
        - ./auth:/var/www
      working_dir: /var/www/html
      networks:
         geoQuiz.net:
           - aliases:
               - api.auth
      depends_on:
        - geoQuiz.db.auth

    geoQuiz.api.geo:
      image: 'canals/php:latest'
      ports:
        - '2082:80'
      volumes:
        - ./geo:/var/www/html
        - ./geo:/var/www
      working_dir: /var/www/html
      networks:
         geoQuiz.net:
           - aliases:
               - api.geo
      depends_on:
        - geoQuiz.db.geo

    adminer:
      image: adminer
      ports:
        - '8080:8080'
      networks:
        - geoQuiz.net

    geoQuiz.db.geo:
      image: 'mariadb:latest'
      command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
      env_file: db.env
      ports:
        - '3307:3306'
      networks:
        - geoQuiz.net

    geoQuiz.db.auth:
        image: 'mariadb:latest'
        command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
        env_file: db.env
        ports:
            - '3308:3306'
        networks:
            - geoQuiz.net


    geoQuiz.db.directus:
          image: postgis/postgis:13-master
          # Required when running on platform other than amd64, like Apple M1/M2:
          # platform: linux/amd64
          volumes:
            - ./data/database:/var/lib/postgresql/data
          environment:
            POSTGRES_USER: "directus"
            POSTGRES_PASSWORD: "directus"
            POSTGRES_DB: "directus"
          networks:
                - geoQuiz.net

    cache:
            image: redis:6
            networks:
            - geoQuiz.net

    geoQuiz.directus:
            image: directus/directus:10.8.3
            ports:
              - 8055:8055
            volumes:
              - ./uploads:/directus/uploads
              # If you want to load extensions from the host
              # - ./extensions:/directus/extensions
            depends_on:
              - cache
              - geoQuiz.db.directus
            environment:
              KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
              SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

              DB_CLIENT: "pg"
              DB_HOST: "database"
              DB_PORT: "5432"
              DB_DATABASE: "directus"
              DB_USER: "directus"
              DB_PASSWORD: "directus"

              CACHE_ENABLED: "true"
              CACHE_STORE: "redis"
              REDIS: "redis://cache:6379"

              ADMIN_EMAIL: "admin@example.com"
              ADMIN_PASSWORD: "d1r3ctu5"

              # Make sure to set this in production
              # (see https://docs.directus.io/self-hosted/config-options#general)
              # PUBLIC_URL: "https://directus.example.com"

            # Environment variables can also be defined in a file (for example `.env`):
            # env_file:
            #	  - .env

            networks:
              - geoQuiz.net

    geoQuiz.frontend:
      image: php:7.4-apache
      ports:
            - '2083:80'
      volumes:
            - ./frontend:/var/www/html
            - ./frontend:/var/www
      working_dir: /var/www/html
      networks:
                - geoQuiz.net