version: "3"
networks:
  geoQuiz.net:
    driver: bridge
services:
  geoQuiz.api.auth:
    image: 'canals/php:8.2'
    ports:
      - '37201:80'
    volumes:
      - ./back/API-Auth/public:/var/www/html
      - ./back/API-Auth:/var/www
    working_dir: /var/www
    networks:
      geoQuiz.net:
        aliases:
          - api.auth
    depends_on:
      - geoQuiz.db.auth

  geoQuiz.api.geo:
    image: 'canals/php:8.2'
    ports:
      - '37202:80'
    volumes:
      - ./back/API-Geolo/public:/var/www/html
      - ./back/API-Geolo:/var/www
    working_dir: /var/www
    networks:
      geoQuiz.net:
          aliases:
            - api.geo
    depends_on:
      - geoQuiz.db.geo

  adminer:
    image: adminer
    ports:
      - '37203:8080'
    networks:
      - geoQuiz.net
    command: php -S 0.0.0.0:8080 -t /var/www/html

  geoQuiz.db.geo:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: component/db.env
    ports:
      - '37204:3306'
    networks:
      - geoQuiz.net

  geoQuiz.db.auth:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: component/db.env
    ports:
      - '37205:3306'
    networks:
      - geoQuiz.net

  geoQuiz.db.directus:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./back/data/database:/var/lib/postgresql/data
    env_file:
      - component/dbDirectus.env
    environment:
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    networks:
      - geoQuiz.net

  cache:
    image: redis:6
    networks:
      - geoQuiz.net

  geoQuiz.directus:
    image: directus/directus:10.9.0
    ports:
      - "37206:8055"
    volumes:
      - ./back/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - geoQuiz.db.directus
    environment:
      - KEY=255d861b-5ea1-5996-9aa3-922530ec40b1
      - SECRET=6116487b-cda1-52c2-b5b5-c8022c45e263
      - DB_CLIENT=pg
      - DB_HOST=geoQuiz.db.directus
      - DB_PORT=5432
      - DB_DATABASE=geoquiz
      - DB_USER=Navia
      - DB_PASSWORD=selie
      - CACHE_ENABLED=false
      - CACHE_STORE=redis
      - REDIS=redis://cache:6379
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=d1r3ctu5
      - DIRECTUS_CORS_ENABLED=true
      - DIRECTUS_CORS_ORIGIN=http://localhost,http://docketu.iutnc.univ-lorraine.fr
      - DIRECTUS_CORS_METHODS=GET,POST,PUT,DELETE,PATCH,OPTIONS
      - DIRECTUS_CORS_HEADERS=Content-Type,Authorization
    networks:
      - geoQuiz.net

  geoQuiz.frontend:
    image: php:7.4-apache
    ports:
      - '37207:80'
    volumes:
      - ./front/GeoQuiz/dist:/var/www/html
    working_dir: /var/www
    networks:
      - geoQuiz.net

  Directus.api.geo:
    image: 'canals/php:8.2'
    ports:
      - '37208:80'
    volumes:
      - ./back/API-Directus/public:/var/www/html
      - ./back/API-Directus:/var/www
    working_dir: /var/www
    networks:
      geoQuiz.net:
        aliases:
          - api.geo
    depends_on:
      - geoQuiz.db.directus