version: "3"
networks:
  geoQuiz.net:
    driver: bridge
services:
  geoQuiz.api.auth:
    image: 'canals/php:8.2'
    ports:
      - '37201:80'
    volumes:
      - ./back/API-Auth/public:/var/www/html
      - ./back/API-Auth:/var/www
    working_dir: /var/www
    networks:
      geoQuiz.net:
        aliases:
          - api.auth
    depends_on:
      - geoQuiz.db.auth

  geoQuiz.api.geo:
    image: 'canals/php:8.2'
    ports:
      - '37202:80'
    volumes:
      - ./back/API-Geolo/public:/var/www/html
      - ./back/API-Geolo:/var/www
    working_dir: /var/www
    networks:
      geoQuiz.net:
          aliases:
            - api.geo
    depends_on:
      - geoQuiz.db.geo

  adminer:
    image: adminer
    ports:
      - '37203:8080'
    networks:
      - geoQuiz.net
    command: php -S 0.0.0.0:8080 -t /var/www/html

  geoQuiz.db.geo:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: component/db.env
    ports:
      - '37204:3306'
    networks:
      - geoQuiz.net

  geoQuiz.db.auth:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: component/db.env
    ports:
      - '37205:3306'
    networks:
      - geoQuiz.net


  geoQuiz.db.directus:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./back/data/database:/var/lib/postgresql/data
    env_file:
      - component/dbDirectus.env
    environment:
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    networks:
      - geoQuiz.net

  cache:
    image: redis:6
    networks:
      - geoQuiz.net

  geoQuiz.directus:
    image: directus/directus:10.8.3
    ports:
      - "37206:8055"
    volumes:
      - ./back/uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - geoQuiz.db.directus
    env_file:
      - component/directus.env


      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"

    # Environment variables can also be defined in a file (for example `.env`):
    # env_file:
    #	  - .env

    networks:
      - geoQuiz.net

  geoQuiz.frontend:
    image: php:7.4-apache
    ports:
      - '37207:80'
    volumes:
      - ./front/GeoQuiz/dist:/var/www/html
    working_dir: /var/www
    networks:
      - geoQuiz.net